def findTheDifference(s: str, t: str) -> str:
    """
    You are given two strings s and t.

    String t is generated by random shuffling string s and then add one more letter at a random position.

    Return the letter that was added to t.

    >>> findTheDifference("abcd", "abcde")
    'e'
    >>> findTheDifference('', 'y')
    'y'
    >>> findTheDifference("a", "aa")
    'a'
    >>> findTheDifference("ae", "aea")
    'a'

    """
    a = 0
    for char in s + t:
        a ^= ord(char)
    return chr(a)


if __name__ == '__main__':
    import doctest
    doctest.testmod(verbose=True)